### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by pouledodue** [bbonnin/pulsar-express#13]
Hi
Is there a config env_var for the port?
I run docker with `-p 3001:3000` (because grafana is already on port 3000)
but the web interface keeps calling port 3000:
```
[Error] XMLHttpRequest cannot load http://localhost:3000/api/admin/v2/clusters?u=http://host.docker.internal:8080 due to access control checks.
```

**Comment by bbonnin** [comment]
Hi,
You can set the var NUXT_PORT.
For example: `docker run -it -e NUXT_PORT=3001 -p 3001:3001 -e PE_CONNECTION_URL=http://host.docker.internal:8080 pulsar-express`
