### ISSUE TITLE
any rest api to add/remove the connector in Pulsar?

### ISSUE THREAD

**Issue by helxsz** [bbonnin/pulsar-express#14]
I am using Pulsar IO with support for the Debezium source connectors to get stream changes from your databases.

From the documentation, it is clear how to connect to MYSQL,

$ bin/pulsar-admin source localrun  --sourceConfigFile debezium-mysql-source-config.yaml
to monitor the connector

bin/pulsar-admin functions getstatus \
    --tenant <tenant> \
    --namespace <namespace> \
    --name <connector-name>

And does pulsar-express provide any rest API to add/remove connector?

**Comment by bbonnin** [comment]
Hi,
pulsar-express is a Web UI for Pulsar, it provides API for an internal use.
Maybe you could check what Pulsar provides here: https://pulsar.apache.org/functions-rest-api/?version=2.4.0
