### ISSUE TITLE
Which auth providers are supported? (yet) 

### ISSUE THREAD

**Issue by KannarFr** [bbonnin/pulsar-express#3]
Hi @bbonnin,

I just tried it and it seems that HTTP Basic Auth is the only one supported. Am I right? Do you plan to add other like the JWT one?

I can help you to add it. :)

**Comment by bbonnin** [comment]
Hello,
In fact, at the moment, no security is supported :(
Feel free  to contribute ;)

**Comment by bbonnin** [comment]
Hi,

In v0.3.0, you can define a connection that uses a token (see: https://pulsar.apache.org/docs/en/security-token-admin/).
A first step ;)

**Comment by KannarFr** [comment]
Hi @bbonnin, thanks!
