### ISSUE TITLE
How to point Pulsar-express to Apache Pulsar Cluster

### ISSUE THREAD

**Issue by Ceyword** [bbonnin/pulsar-express#68]
Hello,
Thank you for this very useful Apache Pulsar GUI.
I have an Azure VM with AlmaLinux OS.
VM hosts Podman.
Podman contains:
	1- Apache Pulsar all-in-one running container.
	2- Pulsar-express (bbonnin/pulsar-express) running container.

Pulsar clients successfully connect to Apache Pulsar over the internet at pulsar://xx.xxx.xx.xxx:6650

I can successfully access Pulsar-express remotely at http://xx.xxx.xx.xxx:3000 

My question: **how do I point Pulsar-express to the Apache Pulsar cluster at http://xx.xxx.xx.xxx:6650?**

I have tried both http://xx.xxx.xx.xxx:8080 and http://xx.xxx.xx.xxx:6650 as connection values (in the Connections tab of Pulsar-express) without success.

Upon observation, both timeout(504) in the requests http://xx.xxx.xx.xxx:3000/api/admin/v2/clusters?n=http://xx.xxx.xx.xxx:8080 and http://xx.xxx.xx.xxx:3000/api/admin/v2/clusters?n=http://xx.xxx.xx.xxx:6650.

**Comment by bbonnin** [comment]
Hello @Ceyword ,
If I understand well your context, you have two podman containers (one for Pulsar, one for pulsar-express).
I think you should have a look on how to communicate between podmancontainers.
For example with Docker containers: https://www.tutorialworks.com/container-networking/
Hope that helps !

**Comment by Ceyword** [comment]
Hello @bbonnin ,
Thank you for your response, and apologies for the late reply. AlmaLinux web console exposes the internal IP address of containers. I added it (internal IP address) to Pulsar-express connections list and everything worked life a charm.
Thank you again.
